# ----------------------------------------------------------------------------
#
# Package             : ginkgo
# Source Repo         : https://github.com/onsi/ginkgo
# Travis Job Link     : https://travis-ci.com/github/santosh653/ginkgo
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
language: go
go:
  - 1.14
  - 1.15
  - tip

#cache:
# directories:
#  - $GOPATH/pkg/mod

# allow internal package imports, necessary for forked repositories
# go_import_path: github.com/onsi/ginkgo

install:
  - GO111MODULE="on" go install github.com/open-cluster-management/multicloud-operators-foundation
  - export PATH=$GOPATH/bin:$PATH
  - go mod vendor

script:
  - make build
  
